### ISSUE TITLE
Support for OkHttp client and Retrofit

### ISSUE THREAD

**Issue by mgawinec** [akamai/AkamaiOPEN-edgegrid-java#16]
It would be great to have a binding for [OkHttp client](http://square.github.io/okhttp/).

OkHttp client is used by [Retrofit](https://square.github.io/retrofit/), so that would provide immediate binding for Retrofit as well. Retrofit is great support for those who do not like to work on HTTP/JSON/etc. level (like REST-assured does), but prefers to think in terms of Java beans.

Technically, [request interceptors](https://github.com/square/okhttp/wiki/Interceptors) could be use for that.

**Comment by elreydetodo** [comment]
We haven't had any further customer requests for this library, and to my knowledge it's not particularly popular among modern Java applications. I'm going to close the request, but we can always reconsider if anyone else requests it.

**Comment by IbrahemSalah** [comment]
@elreydetodo Can you please double check it again, As it's very common used library
