### ISSUE TITLE
Binding for java.net

### ISSUE THREAD

**Issue by mgawinec** [akamai/AkamaiOPEN-edgegrid-java#17]
Some users may not want to use any off-the-shelf HTTP client (like Apache or OkHttp). For those users it might be useful to have a binding based on JDK [`java.net`](http://docs.oracle.com/javase/8/docs/api/java/net/package-summary.html) package only.

A binding would sign directly [`java.net.URLConnection`](http://docs.oracle.com/javase/8/docs/api/java/net/URLConnection.html). [Here](http://stackoverflow.com/questions/2793150/using-java-net-urlconnection-to-fire-and-handle-http-requests) are examples of sending HTTP requests with this class.

**Comment by elreydetodo** [comment]
We haven't had any further customer requests for this library, and to my knowledge it's not particularly popular among modern Java applications. I'm going to close the request, but we can always reconsider if anyone else requests it.
