### ISSUE TITLE
Need JDK 1.6 compatible code

### ISSUE THREAD

**Issue by bachi305** [akamai/AkamaiOPEN-edgegrid-java#27]
Akamai Team,

Some of our applications still using JDK 1.6. 

Please could you get JDK 1.6 compatible library files to create signature.

Regards
Vijay
Macys

**Comment by elreydetodo** [comment]
@bachi305 I'm afraid we have no plan to produce a JDK6-compatible version. In fact the next release will be dropping JDK7 support (it will be compiled and build with JDK8, so the JAR file format will be incompatible). JDK6 and JDK7 are both past their end of support life. Your project really needs to upgrade to a supported version of Java.
