### ISSUE TITLE
What is necessary to use standard jax-rs?

### ISSUE THREAD

**Issue by mkueng1** [akamai/AkamaiOPEN-edgegrid-java#34]
I don't want to / cannot use any additional 3rd party library for REST calls. What is necessary to just use standard jax-rs?

**Comment by elreydetodo** [comment]
I don't have any experience with JAX-RS, but the basic idea is that you need to change the user agent to inject a header named "Authorization" in a similar manner to the Apache HTTP Client implementation:

https://github.com/akamai/AkamaiOPEN-edgegrid-java/blob/master/edgegrid-signer-apache-http-client/src/main/java/com/akamai/edgegrid/signer/apachehttpclient/ApacheHttpClientEdgeGridRequestSigner.java#L102

That header depends on the rest of the requesting being constructed, including the body in the case of a POST request.

**Comment by mkueng1** [comment]
Thanks for pointing me to that code snippet. This should work for me.
Build up the akamai core Request next to the Jax-RS request, get the signature to be added as Authorization http header.
